# Is triggered:
#   1. curl 
#   2. manuell 
name: Clear

# Controls when the action will run. 
on:
  # Can be triggered with cURL
  repository_dispatch:
    types: [clear]

  # Can be triggered manually
  workflow_dispatch:
    inputs:
      symbolParam:
        description: 'DUMMY - xxx'
        required: false
        default: 'XXX'

  schedule:
  # Every saturday
  - cron: "0 0 * * SAT"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run curl clear
        run: |
          echo "Start Clear Reservation ..."

          sed -i '/\/\/BEGIN_PLACEHOLDER/,/\/\/END_PLACEHOLDER/c\\/\/BEGIN_PLACEHOLDER\nvar dynamicButton = document.getElementById("DISABLE_BUTTON_PLACEHOLDER1");\nif(dynamicButton){\ndynamicButton.disabled = true;\n}dynamicButton = document.getElementById("DISABLE_BUTTON_PLACEHOLDER2");\nif(dynamicButton){\ndynamicButton.disabled = true;\n}dynamicButton = document.getElementById("DISABLE_BUTTON_PLACEHOLDER3");\nif(dynamicButton){\ndynamicButton.disabled = true;\n}\ndynamicButton = document.getElementById("DISABLE_BUTTON_PLACEHOLDER4");\nif(dynamicButton){\ndynamicButton.disabled = true;\n}\ndynamicButton = document.getElementById("DISABLE_BUTTON_PLACEHOLDER5");\nif(dynamicButton){\ndynamicButton.disabled = true;\n}\n\/\/END_PLACEHOLDER' hopf-it/reservation-form.html

          git config user.email ${{secrets.MAIL_ADRESS}}
          git config user.name "Markus Hopf"
          git add *
          git commit -am "Github ${{github.event_name}} ${{github.event.action}}" --allow-empty
          git push          

      - name: Send result via email
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.ionos.de
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Clear Reservation Hopf-it.de
          # Read file contents as body:
          body: file://hopf-it/reservation-email.html
          to: ${{secrets.MAIL_ADRESS}}
          from: Hopf-it.de Live Online Video Beratung
          # Optional content type (defaults to text/plain):
          content_type: text/html
          # Optional attachments:
          attachments: hopf-it/images/PayPal.png, hopf-it/images/GoogleMeet.png, hopf-it/images/data/thumbMaxKlein4.jpg
